!coverage.py: This is a private format, don't read it directly!{"lines": {"/home/debian/gmopg/gmopg/errors.py": [4, 6, 12, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157], "/home/debian/gmopg/gmopg/__init__.py": [2, 3, 4, 6, 7, 10, 12, 13, 15, 18, 21, 22, 25, 27, 28, 29, 31, 32, 34, 36, 41, 42, 44, 45, 46, 47, 49, 50, 51, 52, 54, 57, 59, 60, 62, 64, 66, 68, 71, 73, 74, 76, 78, 81, 82, 84, 85, 86, 89, 91, 100, 101, 103, 111, 112, 114, 122, 123, 125, 132, 133, 136, 138, 154, 155, 157, 167, 168, 170, 180, 181, 183, 197, 198, 201, 203, 211, 212, 215, 217, 233, 234, 236, 238, 266, 267, 269, 271, 283, 284, 286, 309, 310, 313, 315]}}